{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "Barcode Command API",
        "description": "Sipari\u015fi faturala\u015ft\u0131rarak g\u00f6nderiye \u00e7eviren, g\u00f6nderiyi g\u00fcncelleyen ve iptal eden metodlar\u0131n yer ald\u0131\u011f\u0131 API'd\u0131r. | It is the API that converts the order to the shipment by invoicing, updating and cancelling the shipment.",
        "termsOfService": "http://swagger.io/terms/"
    },
    "basePath": "/mngapi/api/barcodecmdapi",
    "paths": {
        "/createbarcode": {
            "post": {
                "tags": [
                    "BarcodeCommand"
                ],
                "summary": "Create Barcode",
                "description": "Sipari\u015fi faturala\u015ft\u0131rarak g\u00f6nderiye \u00e7evirir ve sonucunda bir barkod etiketi \u00fcretir. | Invoicing the order to the shipment and producing a barcode label as a result.",
                "operationId": "CreatebarcodePost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "createBarcodeRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CreateBarcodeRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Shipment barcode created",
                        "schema": {
                            "$ref": "#/definitions/CreateBarcodeResponse"
                        },
                        "examples": {
                            "application/json": {
                                "referenceId": "SIPARIS34567",
                                "invoiceId": "564645774",
                                "shipmentId": "4536457657",
                                "barcodes": [
                                    {
                                        "pieceNumber": 1,
                                        "value": "Barcode1"
                                    },
                                    {
                                        "pieceNumber": 2,
                                        "value": "Barcode2"
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/updateshipment": {
            "put": {
                "tags": [
                    "BarcodeCommand"
                ],
                "summary": "Update Shipment",
                "description": "\u0130lgili referans ve g\u00f6nderi numaras\u0131na ait g\u00f6nderiyi g\u00fcnceller. | Updates the shipment of the relevant reference and shipment number.",
                "operationId": "UpdateshipmentPut",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "updateShipmentRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/UpdateShipmentRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Shipment updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/cancelshipment": {
            "put": {
                "tags": [
                    "BarcodeCommand"
                ],
                "summary": "Cancel Shipment",
                "description": "\u0130lgili referans ve g\u00f6nderi numaras\u0131na ait g\u00f6nderiyi iptal eder. | Cancels the shipment of the relevant reference and shipment number.",
                "operationId": "CancelshipmentPut",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "createCustomerRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CancelShipmentRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Shipment canceled",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "CreateBarcodeRequest": {
            "required": [
                "referenceId"
            ],
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order\r\nSipari\u015f Numaras\u0131",
                    "type": "string"
                },
                "billOfLandingId": {
                    "description": "Bill Of LandingId\r\n\u0130rsaliye Numaras\u0131",
                    "type": "string"
                },
                "isCOD": {
                    "format": "int32",
                    "description": "Indicates whether it is Cash On Delivery.\r\nKap\u0131da \u00d6deme mi?",
                    "type": "integer"
                },
                "codAmount": {
                    "format": "double",
                    "description": "Cash on Delivery Amount\r\nKap\u0131da \u00d6deme Miktar\u0131",
                    "type": "number"
                },
                "printReferenceBarcodeOnError": {
                    "format": "int32",
                    "description": "Create Reference Label when an error occurs creating Barcode Label\r\nBarkod Etiketi olu\u015fturulurken hata olursa yerine Referans Etiketini olu\u015ftur.",
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "additionalContent1": {
                    "type": "string"
                },
                "additionalContent2": {
                    "type": "string"
                },
                "additionalContent3": {
                    "type": "string"
                },
                "additionalContent4": {
                    "type": "string"
                },
                "orderPieceList": {
                    "uniqueItems": false,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderPieceList"
                    }
                },
                "packagingType": {
                    "type": "integer",
                    "format": "int32"
                }
            },
            "example": {
                "referenceId": "SIPARIS34567",
                "billOfLandingId": "\u0130rsaliye 1",
                "isCOD": 0,
                "codAmount": 0,
                "packagingType": 2,
                "printReferenceBarcodeOnError": 0,
                "message": "Mesaj 1",
                "additionalContent1": "",
                "additionalContent2": "",
                "additionalContent3": "",
                "additionalContent4": "",
                "orderPieceList": [
                    {
                        "barcode": "SIPARIS34567_PARCA1",
                        "desi": 2,
                        "kg": 1,
                        "content": "Par\u00e7a a\u00e7\u0131klama 1"
                    },
                    {
                        "barcode": "SIPARIS34567_PARCA2",
                        "desi": 2,
                        "kg": 3,
                        "content": "Par\u00e7a a\u00e7\u0131klama 2"
                    }
                ]
            }
        },
        "OrderPieceList": {
            "required": [
                "barcode",
                "desi",
                "kg"
            ],
            "type": "object",
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "desi": {
                    "format": "int32",
                    "type": "integer"
                },
                "kg": {
                    "format": "int32",
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "CreateBarcodeResponse": {
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order\r\nSipari\u015f Numaras\u0131",
                    "type": "string"
                },
                "invoiceId": {
                    "description": "Invoice Number\r\nFatura Numaras\u0131",
                    "type": "string"
                },
                "shipmentId": {
                    "description": "Identity Number of Shipment\r\nG\u00f6nderi Numaras\u0131",
                    "type": "string"
                },
                "barcodes": {
                    "uniqueItems": false,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/BarcodeInfo"
                    }
                }
            }
        },
        "BarcodeInfo": {
            "type": "object",
            "properties": {
                "pieceNumber": {
                    "format": "int32",
                    "description": "Shipment Piece Number \r\nPar\u00e7a Say\u0131s\u0131",
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "UpdateShipmentRequest": {
            "required": [
                "referenceId",
                "shipmentId"
            ],
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order\r\nSipari\u015f Numaras\u0131",
                    "type": "string"
                },
                "shipmentId": {
                    "description": "Identity Number of Shipment\r\nG\u00f6nderi Numaras\u0131",
                    "type": "string"
                },
                "billOfLandingId": {
                    "description": "Bill Of LandingId\r\n\u0130rsaliye Numaras\u0131",
                    "type": "string"
                },
                "isCOD": {
                    "format": "int32",
                    "description": "Indicates whether it is Cash On Delivery.\r\nKap\u0131da \u00d6deme mi?",
                    "type": "integer"
                },
                "codAmount": {
                    "format": "double",
                    "description": "Cash on Delivery Amount\r\nKap\u0131da \u00d6deme Miktar\u0131",
                    "type": "number"
                },
                "orderPieceList": {
                    "uniqueItems": false,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderPieceList"
                    }
                }
            },
            "example": {
                "referenceId": "SIPARIS34567",
                "shipmentId": "838302813413",
                "billOfLandingId": "\u0130rsaliye 1",
                "isCOD": 0,
                "codAmount": 0,
                "orderPieceList": [
                    {
                        "barcode": "SIPARIS34567_PARCA1",
                        "desi": 3,
                        "kg": 1,
                        "content": "Par\u00e7a a\u00e7\u0131klama 1"
                    },
                    {
                        "barcode": "SIPARIS34567_PARCA2",
                        "desi": 2,
                        "kg": 3,
                        "content": "Par\u00e7a a\u00e7\u0131klama 2"
                    }
                ]
            }
        },
        "CancelShipmentRequest": {
            "required": [
                "referenceId",
                "shipmentId"
            ],
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order\r\nSipari\u015f Numaras\u0131",
                    "type": "string"
                },
                "shipmentId": {
                    "description": "Identity Number of Shipment\r\nG\u00f6nderi Numaras\u0131",
                    "type": "string"
                }
            },
            "example": {
                "referenceId": "2315665",
                "shipmentId": "838302813413"
            }
        }
    },
    "securityDefinitions": {
        "api-key-1": {
            "description": "",
            "in": "header",
            "name": "X-IBM-Client-Id",
            "type": "apiKey"
        },
        "api-key-2": {
            "description": "",
            "in": "header",
            "name": "X-IBM-Client-Secret",
            "type": "apiKey"
        }
    },
    "security": [
        {
            "api-key-2": [],
            "api-key-1": []
        }
    ],
    "schemes": [
        "https"
    ],
    "host": "testapi.mngkargo.com.tr"
}