{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "Plus Query API",
        "description": "\u0130ade g\u00f6nderilerini listeleyen, g\u00f6nderi hareketlerini irsaliye numaras\u0131na g\u00f6re getiren, g\u00f6nderi bilgilerini tarih veya barkoda g\u00f6re getiren, g\u00f6nderi teslimat problemlerini listeleyen API'd\u0131r. | This is the API that checks return order, tracks shipment by bill of landing id, get shipment informations by date or barcode, lists shipment delivery problems.",
        "termsOfService": "http://swagger.io/terms/"
    },
    "basePath": "/mngapi/api/plusqueryapi",
    "paths": {
        "/checkReturnOrder": {
            "post": {
                "tags": [
                    "PlusQuery"
                ],
                "summary": "Check Return Order",
                "description": "Belirtilen kriterlere ait iade g\u00f6nderi listesini getirir. | Returns the return shipment list for the specified criteria.",
                "operationId": "CheckReturnOrderPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "checkReturnOrderRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CheckReturnOrderRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "uniqueItems": false,
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CheckReturnOrderResponse"
                            }
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "paymentType": "ALICI_ODER",
                                    "orderDate": "9.01.2020 00:00:00",
                                    "referenceId": "N85B7",
                                    "shipperFullName": "Volkan Volkan",
                                    "returnShipmentDate": "10-01-2020 10:43:17",
                                    "shipmentId": "179509647303",
                                    "invoiceSerialNumber": "FM",
                                    "invoiceNumber": "306560",
                                    "invoiceType": "ATF",
                                    "numberOfPieces": "1",
                                    "kgdesi": "3",
                                    "total": "36,82",
                                    "deliveryDateTime": " ",
                                    "shipmentLastMove": "FATURA KESILDI (10/01/2020)",
                                    "shipmentFollowUrl": "http://service.mngkargo.com.tr/iactive/popup/KargoTakip/link1.asp?k=179509647303",
                                    "eventSequence": "1",
                                    "eventStatus": "Sipari\u015f Kargoya Verildi",
                                    "eventDateTime": "10-01-2020 10:43:17"
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Return order checked",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/trackShipmentByBillofLandingId/{BillofLandingId}": {
            "get": {
                "tags": [
                    "PlusQuery"
                ],
                "summary": "Track Shipment By Bill of Landing Id",
                "description": "\u0130lgili irsaliye numaras\u0131na ait g\u00f6nderi hareketlerini getirir. E\u011fer sipari\u015f faturala\u015fm\u0131\u015f ise bu bilgi elde edilebilir. | Returns the shipment movements of the relevant bill of landing id. If the order has been invoiced, this information can be obtained.",
                "operationId": "TrackShipmentByBillofLandingIdByBillofLandingIdGet",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "BillofLandingId",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "uniqueItems": false,
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/TrackShipmentByBillofLandingIdResponse"
                            }
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "referenceId": "SIPARIS_28654",
                                    "eventSequence": "1",
                                    "eventStatus": "G\u00f6nderi Haz\u0131rland\u0131",
                                    "eventDateTime": "12-02-2019 10:30:45",
                                    "location": "Atalar \u015eube",
                                    "locationAddress": "\u0130STANBUL (KARTAL)",
                                    "locationPhone": "0216 494 28 84- 494 28 58",
                                    "deliveryDateTime": "13-02-2019 14:56",
                                    "deliveryTo": "Sema Kudu",
                                    "description": "",
                                    "pieceTotal": "1"
                                },
                                {
                                    "referenceId": "SIPARIS_28654",
                                    "eventSequence": "2",
                                    "eventStatus": "Transfer A\u015famas\u0131nda",
                                    "eventDateTime": "12-02-2019 10:30:55",
                                    "location": "Marmara Aktarma",
                                    "locationAddress": "\u0130STANBUL",
                                    "locationPhone": "0216 494 28 84- 494 28 58",
                                    "deliveryDateTime": "13-02-2019 14:56",
                                    "deliveryTo": "Sema Kudu",
                                    "description": "",
                                    "pieceTotal": "1"
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Shipment not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/getShipmentByBarcode/{barcode}": {
            "get": {
                "tags": [
                    "PlusQuery"
                ],
                "summary": "Get Shipment By Barcode",
                "description": "\u0130lgili barkoda ait g\u00f6nderi bilgilerini getirir. E\u011fer sipari\u015f faturala\u015fm\u0131\u015f ise bu bilgi elde edilebilir. | Returns the shipment information of the relevant barcode. If the order has been invoiced, this information can be obtained.",
                "operationId": "GetShipmentByBarcodeByBarcodeGet",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "barcode",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "uniqueItems": false,
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/GetShipmentByBarcodeResponse"
                            }
                        },
                        "examples": {
                            "application/json": {
                                "shipment": {
                                    "shipmentServiceType": "STANDART_TESL\u0130MAT",
                                    "packagingType": "PAKET",
                                    "paymentType": "GONDERICI_ODER",
                                    "deliveryType": "ADRESE_TESLIM",
                                    "referenceId": "SIPARIS34567",
                                    "shipmentId": "931001401082",
                                    "shipmentSerialNumber": "FM",
                                    "shipmentNumber": "306971",
                                    "shipmentDateTime": "20-02-2020 15:59:51",
                                    "pieceCount": 0,
                                    "totalKg": 1,
                                    "totalDesi": 1,
                                    "totalKgDesi": 1,
                                    "total": 34.61,
                                    "kdv": 6.23,
                                    "finalTotal": 40.84,
                                    "shipmentStatusCode": 5,
                                    "isMarketPlaceShipment": 0,
                                    "isMarketPlacePays": 0,
                                    "shipperBranch": "ATLAS",
                                    "billOfLandingId": "\u0130rsaliye 1",
                                    "isCOD": 0,
                                    "codAmount": "0",
                                    "content": "\u0130\u00e7erik 1",
                                    "estimatedDeliveryDate": "21-02-2020",
                                    "isDelivered": 0
                                },
                                "shipmentPieceList": [
                                    {
                                        "numberOfPieces": 1,
                                        "kgDesi": 2,
                                        "barcode": "SIPARIS34567_PARCA1",
                                        "desi": 2,
                                        "kg": 1,
                                        "content": "Par\u00e7a a\u00e7\u0131klama 1"
                                    },
                                    {
                                        "numberOfPieces": 1,
                                        "kgDesi": 2,
                                        "barcode": "SIPARIS34567_PARCA2",
                                        "desi": 2,
                                        "kg": 1,
                                        "content": "Par\u00e7a a\u00e7\u0131klama 2"
                                    }
                                ],
                                "shipper": {
                                    "customerId": 847555,
                                    "refCustomerId": "",
                                    "city": "",
                                    "district": "",
                                    "address": "",
                                    "bussinessPhoneNumber": "",
                                    "email": "",
                                    "taxOffice": "",
                                    "taxNumber": "",
                                    "fullName": "",
                                    "homePhoneNumber": "",
                                    "mobilePhoneNumber": ""
                                },
                                "recipient": {
                                    "refCustomerId": "",
                                    "city": "\u0130stanbul",
                                    "district": "Levent",
                                    "address": "H\u00fcrriyet Mah. Ahmet Yesevi Cad. \u0130kizler Sok.",
                                    "bussinessPhoneNumber": "",
                                    "email": "email@ornekemail.com",
                                    "taxOffice": "",
                                    "taxNumber": "",
                                    "fullName": "Ad 2",
                                    "homePhoneNumber": "5555555555",
                                    "mobilePhoneNumber": ""
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Shipment not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/getShipmentDeliveryProblems": {
            "post": {
                "tags": [
                    "PlusQuery"
                ],
                "summary": "Get Shipment Delivery Problems",
                "description": "Belirtilen kriterlere ait g\u00f6nderi teslimat problemleri listesini getirir. | Returns the shipment delivery problems list for the specified criteria.",
                "operationId": "GetShipmentDeliveryProblemsPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "getShipmentDeliveryProblemsRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/GetShipmentDeliveryProblemsRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "uniqueItems": false,
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/GetShipmentDeliveryProblemsResponse"
                            }
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "isCOD": 0,
                                    "shipmentServiceType": "STANDART_TESL\u0130MAT",
                                    "packagingType": "PAKET",
                                    "paymentType": "GONDERICI_ODER",
                                    "deliveryType": "ADRESE_TESLIM",
                                    "isConfirmed": 1,
                                    "isRecipientRejected": 0,
                                    "isDelivered": 0,
                                    "isEMailSended": 0,
                                    "isAnswered": 1,
                                    "isAnswerApprovedorRejected": 0,
                                    "shipmentDate": "24-02-2020",
                                    "invoiceId": "FM-306994",
                                    "pieceCount": "1",
                                    "totalKgDesi": "1",
                                    "shipperBranch": "ATLAS",
                                    "recipientBranch": "\u015e\u0130R\u0130NEVLER",
                                    "recipient_Name": "ASTEK B\u0130LG\u0130SAYAR TEK DANI\u015e E\u011e\u0130T\u0130M H\u0130ZM",
                                    "recipient_City": "\u0130STANBUL",
                                    "recipient_District": "BAH\u00c7EL\u0130EVLER",
                                    "recipient_PhoneNumber": "5551112233",
                                    "recipient_BussinessPhoneNumber": "5326536253",
                                    "recipient_HomePhoneNumber": "5326536253",
                                    "returnRequestId": "1119",
                                    "returnRequestDateTime": "04-03-2020 09:54:53",
                                    "requestReason": "\u015eubeden Teslim Edilecek Kargo",
                                    "returnReason": "ASDAS",
                                    "isShipmentRejected": 0,
                                    "deliveryTo": " ",
                                    "answerDate": "4.03.2020 00:00:00",
                                    "codAmountFinalTotal": "31,85"
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Shipment delivery problems not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/getTtiList/{ttiNo}": {
            "get": {
                "tags": [
                    "PlusQuery"
                ],
                "summary": "GetTtiListByTtiNo_GET",
                "description": "",
                "operationId": "getTtiList",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "ttiNo",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "uniqueItems": false,
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/GetTtiListResponse"
                            }
                        },
                        "examples": {
                            "application/json": [
                                {
                                    "ttiNo": "4107595",
                                    "courierCode": "E4001",
                                    "courierName": "ATLAS SUBE M\u00dcD\u00dcR",
                                    "ttiDate": "05.02.2023",
                                    "cargoBarcode": "B@6L@E4@E4TFMJHYLAAA6J@",
                                    "kgDesi": "0",
                                    "amount": "1",
                                    "recipient": "TEST M\u00dc\u015eTER\u0130S\u0130",
                                    "shipper": "TEST G\u00d6NDEREN",
                                    "customerNo": "35615719",
                                    "shipmentId": "112784726073",
                                    "invoiceSerial": "FM",
                                    "invoiceNumber": "302859",
                                    "customerRefNo": "",
                                    "pieceNumber": "1",
                                    "shipmentDate": "05.02.2023"
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Shipment not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/GetShipmentInfoByShipmentId/{shipmentId}": {
            "get": {
                "description": "\u0130lgili g\u00f6nderi numaralar\u0131n\u0131n bilgilerini getirir. | Returns the informations of the relevant shipment numbers.",
                "summary": "Get Shipments Status Info By ShipmentId(s)",
                "tags": [
                    "PlusQuery"
                ],
                "operationId": "GetShipmentsStatusInfoByShipmentId(s)",
                "deprecated": false,
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "shipmentId",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "array",
                            "default": "",
                            "items": {
                                "$ref": "#/definitions/GetShipmentInfoByShipmentIdResponse"
                            }
                        },
                        "headers": []
                    },
                    "400": {
                        "description": "Bad Request",
                        "headers": []
                    },
                    "401": {
                        "description": "Unauthorized",
                        "headers": []
                    },
                    "404": {
                        "description": "Shipment not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        },
                        "headers": []
                    },
                    "500": {
                        "description": "Server Error",
                        "headers": []
                    }
                }
            }
        }
    },
    "definitions": {
        "CheckReturnOrderRequest": {
            "title": "CheckReturnOrderRequest",
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order\nSipari\u015f Numaras\u0131",
                    "type": "string"
                },
                "shipmentId": {
                    "description": "Identity Number of Shipment\nG\u00f6nderi Numaras\u0131",
                    "type": "string"
                },
                "invoiceSerialNumber": {
                    "description": "Invoice serail number\nFatura seri numaras\u0131",
                    "type": "string"
                },
                "invoiceNumber": {
                    "description": "Invoice number\nFatura numaras\u0131",
                    "type": "string"
                },
                "barcode": {
                    "description": "Barcode\nBarkod",
                    "type": "string"
                },
                "shipmentReleaseDate": {
                    "description": "Shipment release date\nG\u00f6nderi \u00e7\u0131k\u0131\u015f tarihi",
                    "type": "string"
                }
            }
        },
        "CheckReturnOrderResponse": {
            "title": "CheckReturnOrderResponse",
            "type": "object",
            "properties": {
                "orderDate": {
                    "description": "Order Date\nSipari\u015f Kay\u0131t Tarihi",
                    "type": "string"
                },
                "referenceId": {
                    "description": "Identity Number of Order, ReferenceId must be unique foreach order.\nSipari\u015f Numaras\u0131 , Sipari\u015f numaras\u0131 her sipari\u015f i\u00e7in benzersiz olmal\u0131d\u0131r.",
                    "type": "string"
                },
                "shipperFullName": {
                    "description": "Shipper Full Name \r\nG\u00f6nderici Tam Ad\u0131",
                    "type": "string"
                },
                "returnShipmentDate": {
                    "description": "Return Shipment Date\n\u0130ade G\u00f6nderi Tarihi",
                    "type": "string"
                },
                "shipmentId": {
                    "description": "Identity Number of Shipment\nG\u00f6nderi Numaras\u0131",
                    "type": "string"
                },
                "invoiceSerialNumber": {
                    "description": "Invoice Serial Number \r\nFatura Seri Numaras\u0131",
                    "type": "string"
                },
                "invoiceNumber": {
                    "description": "Invoice Number\nFatura Numaras\u0131",
                    "type": "string"
                },
                "invoiceType": {
                    "description": "Invoice Type\nFatura T\u00fcr\u00fc",
                    "type": "string"
                },
                "numberOfPieces": {
                    "description": "Shipment Total Piece Number\nG\u00f6nderi Toplam Par\u00e7a Say\u0131s\u0131",
                    "type": "string"
                },
                "kgdesi": {
                    "type": "string"
                },
                "total": {
                    "type": "string"
                },
                "billOfLandingId": {
                    "description": "Bill Of LandingId\n\u0130rsaliye Numaras\u0131",
                    "type": "string"
                },
                "deliveryDateTime": {
                    "description": "Delivery DateTime\nTeslim Tarihi",
                    "type": "string"
                },
                "shipmentLastMove": {
                    "description": "Shipment Last Move\nKargo Son Hareket",
                    "type": "string"
                },
                "shipmentFollowUrl": {
                    "description": "Shipment Follow Url\nG\u00f6nderi Takip Linki",
                    "type": "string"
                },
                "eventSequence": {
                    "type": "string"
                },
                "eventStatus": {
                    "description": "Event Status: 1:G\u00f6nderi_Haz\u0131rland\u0131, 2:Transfer_A\u015famas\u0131nda, 3: Teslimat_Birimine_Ula\u015ft\u0131, 4: Al\u0131c\u0131_Adresine_Y\u00f6nlendirildi, 5: Teslim_Edildi, 6:Teslim_Edilemedi, 7:Geri_Geliyor, 8: Destek_Gerekiyor       \r\nG\u00f6nderi Durumu",
                    "type": "string"
                },
                "eventDateTime": {
                    "description": "Event DateTime\nHareket Tarihi",
                    "type": "string"
                },
                "paymentType": {
                    "description": "Payment Type of Order: 1:GONDERICI_ODER, 2:ALICI_ODER,3:PLATFORM_ODER\n\u00d6deme \u015eekli",
                    "type": "string"
                }
            }
        },
        "ProblemDetails": {
            "title": "ProblemDetails",
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "status": {
                    "type": "integer",
                    "format": "int32"
                },
                "detail": {
                    "type": "string"
                },
                "instance": {
                    "type": "string"
                }
            }
        },
        "TrackShipmentByBillofLandingIdResponse": {
            "title": "TrackShipmentByBillofLandingIdResponse",
            "type": "object",
            "properties": {
                "eventSequence": {
                    "type": "string"
                },
                "eventStatus": {
                    "description": "Event Status: 1:G\u00f6nderi_Haz\u0131rland\u0131, 2:Transfer_A\u015famas\u0131nda, 3: Teslimat_Birimine_Ula\u015ft\u0131, 4: Al\u0131c\u0131_Adresine_Y\u00f6nlendirildi, 5: Teslim_Edildi, 6:Teslim_Edilemedi, 7:Geri_Geliyor, 8: Destek_Gerekiyor       \r\nOlay Durumu",
                    "type": "string"
                },
                "eventDateTime": {
                    "description": "Event DateTime\nHareket Tarihi",
                    "type": "string"
                },
                "location": {
                    "description": "Location\nYer",
                    "type": "string"
                },
                "locationAddress": {
                    "description": "Location Address\nAdres",
                    "type": "string"
                },
                "locationPhone": {
                    "description": "Location Phone\nTelefon",
                    "type": "string"
                },
                "deliveryDateTime": {
                    "description": "Delivery DateTime\nTeslim Tarihi",
                    "type": "string"
                },
                "deliveryTo": {
                    "description": "Name and Surname who delivery to shipment.\nG\u00f6nderiyi teslim alan ad\u0131 ve soyad\u0131.",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "pieceTotal": {
                    "description": "Piece Total\nToplam Par\u00e7a Say\u0131s\u0131",
                    "type": "string"
                },
                "referenceId": {
                    "description": "Identity Number of Order\nSipari\u015f Numaras\u0131",
                    "type": "string"
                },
                "shipmentId": {
                    "description": "Identity Number of Shipment\nG\u00f6nderi Numaras\u0131",
                    "type": "string"
                }
            }
        },
        "ShipmentOUT": {
            "title": "ShipmentOUT",
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order\nSipari\u015f Numaras\u0131",
                    "type": "string"
                },
                "shipmentId": {
                    "description": "Identity Number of Shipment\nG\u00f6nderi Numaras\u0131",
                    "type": "string"
                },
                "shipmentSerialNumber": {
                    "type": "string"
                },
                "shipmentNumber": {
                    "type": "string"
                },
                "shipmentDateTime": {
                    "description": "Shipment Date\nG\u00f6nderi Tarihi",
                    "type": "string"
                },
                "pieceCount": {
                    "description": "Shipment Piece Count \r\nG\u00f6nderi Par\u00e7a Say\u0131s\u0131",
                    "type": "integer",
                    "format": "int32"
                },
                "totalKg": {
                    "type": "number",
                    "format": "double"
                },
                "totalDesi": {
                    "type": "number",
                    "format": "double"
                },
                "totalKgDesi": {
                    "type": "number",
                    "format": "double"
                },
                "total": {
                    "type": "number",
                    "format": "double"
                },
                "kdv": {
                    "type": "number",
                    "format": "double"
                },
                "finalTotal": {
                    "type": "number",
                    "format": "double"
                },
                "shipmentStatusCode": {
                    "description": "Shipment Status Code: 1:G\u00f6nderi_Haz\u0131rland\u0131, 2:Transfer_A\u015famas\u0131nda, 3: Teslimat_Birimine_Ula\u015ft\u0131, 4: Al\u0131c\u0131_Adresine_Y\u00f6nlendirildi, 5: Teslim_Edildi, 6:Teslim_Edilemedi, 7:Geri_Geliyor, 8: Destek_Gerekiyor       \r\nG\u00f6nderi Durum Kodu",
                    "type": "integer",
                    "format": "int32"
                },
                "isMarketPlaceShipment": {
                    "type": "integer",
                    "format": "int32"
                },
                "isMarketPlacePays": {
                    "description": "Market Place is pays ?\nG\u00f6nderi \u00fccretini platform mu \u00f6der ?",
                    "type": "integer",
                    "format": "int32"
                },
                "receivingBranch": {
                    "description": "Recipient Branch\nAl\u0131c\u0131 \u015eube",
                    "type": "string"
                },
                "shipperBranch": {
                    "description": "Shipper Branch\nG\u00f6nderici \u015eube",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "billOfLandingId": {
                    "description": "Bill Of LandingId\n\u0130rsaliye Numaras\u0131",
                    "type": "string"
                },
                "shipmentServiceType": {
                    "description": "Shipment service type: 1:STANDART_TESL\u0130MAT, 7:GUN\u0130C\u0130_TESL\u0130MAT, 8:AK\u015eAM_TESL\u0130MAT\nG\u00f6nderi Tipi",
                    "type": "string"
                },
                "isCOD": {
                    "description": "Indicates whether it is Cash On Delivery.\nKap\u0131da \u00d6deme mi?",
                    "type": "integer",
                    "format": "int32"
                },
                "codAmount": {
                    "description": "Cash on Delivery Amount\nKap\u0131da \u00d6deme Miktar\u0131",
                    "type": "string"
                },
                "deliveryType": {
                    "description": "Delivery Type of Order: 1:ADRESE_TESLIM, 2:ALICISI_HABERL\u0130 \r\nTeslim T\u00fcr\u00fc",
                    "type": "string"
                },
                "content": {
                    "description": "Content\nGenel \u0130\u00e7erik Bilgisi",
                    "type": "string"
                },
                "packagingType": {
                    "description": "Package Type of Order:  1:DOSYA, 2:M\u0130, 3:PAKET, 4:KOL\u0130\nKargo Cinsi",
                    "type": "string"
                },
                "estimatedDeliveryDate": {
                    "description": "Shipment Estimated Delivery Date\nG\u00f6nderi Tahmini Teslim Tarihi",
                    "type": "string"
                },
                "deliveryDate": {
                    "description": "Shipment Delivery Date\nG\u00f6nderi Teslim Tarihi",
                    "type": "string"
                },
                "isDelivered": {
                    "description": "Is Shipment Delivered?\nG\u00f6nderi Teslim Edildi Mi?",
                    "type": "integer",
                    "format": "int32"
                },
                "deliveryTo": {
                    "description": "Name and Surname who delivery to shipment.\nG\u00f6nderiyi teslim alan ad\u0131 ve soyad\u0131.",
                    "type": "string"
                },
                "paymentType": {
                    "description": "Payment Type of Order: P:GONDERICI_ODER, U:ALICI_ODER, PL:PLATFORM_ODER\n\u00d6deme T\u00fcr\u00fc",
                    "type": "string"
                }
            }
        },
        "OrderPieceListOUT": {
            "title": "OrderPieceListOUT",
            "type": "object",
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "desi": {
                    "type": "integer",
                    "format": "int32"
                },
                "kg": {
                    "type": "integer",
                    "format": "int32"
                },
                "content": {
                    "type": "string"
                },
                "numberOfPieces": {
                    "type": "integer",
                    "format": "int32"
                },
                "kgDesi": {
                    "type": "integer",
                    "format": "int32"
                }
            },
            "required": [
                "barcode",
                "desi",
                "kg"
            ]
        },
        "CustomerOUT": {
            "title": "CustomerOUT",
            "type": "object",
            "properties": {
                "customerId": {
                    "description": "Identity Number of Customer \r\nM\u00fc\u015fteri Numaras\u0131",
                    "type": "integer",
                    "format": "int64"
                },
                "refCustomerId": {
                    "description": "Identity Number of Customer in their's own system.\nM\u00fc\u015fterinin kendi sistemindeki numaras\u0131",
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "cityName": {
                    "type": "string"
                },
                "districtName": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "bussinessPhoneNumber": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "taxOffice": {
                    "type": "string"
                },
                "taxNumber": {
                    "description": "Tax Office\nVergi Dairesi",
                    "type": "string"
                },
                "fullName": {
                    "description": "Tax Number\nVergi Numaras\u0131",
                    "type": "string"
                },
                "homePhoneNumber": {
                    "type": "string"
                },
                "mobilePhoneNumber": {
                    "type": "string"
                }
            }
        },
        "GetShipmentByBarcodeResponse": {
            "title": "GetShipmentByBarcodeResponse",
            "type": "object",
            "properties": {
                "shipment": {
                    "$ref": "#/definitions/ShipmentOUT"
                },
                "shipmentPieceList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderPieceListOUT"
                    }
                },
                "shipper": {
                    "$ref": "#/definitions/CustomerOUT"
                },
                "recipient": {
                    "$ref": "#/definitions/CustomerOUT"
                }
            }
        },
        "GetShipmentDeliveryProblemsRequest": {
            "title": "GetShipmentDeliveryProblemsRequest",
            "type": "object",
            "properties": {
                "isCOD": {
                    "description": "Indicates whether it is Cash On Delivery.\nKap\u0131da \u00d6deme mi?",
                    "type": "integer",
                    "format": "int32"
                },
                "responseStartDate": {
                    "description": "Response Start Date\nYan\u0131t Ba\u015flang\u0131\u00e7 Tarihi",
                    "type": "string"
                },
                "responseEndDate": {
                    "description": "Response End Date\nYan\u0131t Biti\u015f Tarihi",
                    "type": "string"
                },
                "invoiceId": {
                    "description": "Invoice Number\nFatura Numaras\u0131",
                    "type": "string"
                },
                "responseStatus": {
                    "description": "Response Status : 0:CEVAP BEKLEYENELER - 1:YANITLANAN T\u00dcM\u00dc - 2:YANITLANAN(ONAYLANANLAR) - 3:YANITLANAN(REDDED\u0130LENLER)\nYan\u0131t Durumu",
                    "type": "integer",
                    "format": "int32"
                },
                "isResponseApprovedorRejected": {
                    "description": "Response approved or rejected -- NULLL T\u00dcM\u00dc, 1 ONAYLANLAR  0 RED ED\u0130LENLER.\nYan\u0131t Onayland\u0131 m\u0131? Red mi Edildi ?",
                    "type": "integer",
                    "format": "int32"
                }
            },
            "required": [
                "responseStartDate",
                "responseEndDate",
                "responseStatus"
            ]
        },
        "GetShipmentDeliveryProblemsResponse": {
            "title": "GetShipmentDeliveryProblemsResponse",
            "type": "object",
            "properties": {
                "shipmentDate": {
                    "description": "Shipment Date\nG\u00f6nderi Tarihi",
                    "type": "string"
                },
                "invoiceId": {
                    "description": "Invoice Number\nFatura Numaras\u0131",
                    "type": "string"
                },
                "pieceCount": {
                    "description": "Shipment Piece Count \r\nG\u00f6nderi Par\u00e7a Say\u0131s\u0131",
                    "type": "string"
                },
                "totalKgDesi": {
                    "type": "string"
                },
                "referenceId": {
                    "description": "Identity Number of Shipment\nG\u00f6nderi Numaras\u0131 : Her g\u00f6nderi i\u00e7in benzersiz olmal\u0131d\u0131r.",
                    "type": "string"
                },
                "shipperBranch": {
                    "description": "Shipper Branch\nG\u00f6nderici \u015fube",
                    "type": "string"
                },
                "recipientBranch": {
                    "description": "Recipient Branch\nAl\u0131c\u0131 \u015eube",
                    "type": "string"
                },
                "recipient_Name": {
                    "type": "string"
                },
                "recipient_City": {
                    "type": "string"
                },
                "recipient_District": {
                    "type": "string"
                },
                "recipient_PhoneNumber": {
                    "type": "string"
                },
                "recipient_BussinessPhoneNumber": {
                    "type": "string"
                },
                "recipient_HomePhoneNumber": {
                    "type": "string"
                },
                "returnRequestId": {
                    "description": "Return Request Id\n\u0130ade \u0130stek Numaras\u0131",
                    "type": "string"
                },
                "returnRequestDateTime": {
                    "description": "Return Request DateTime\n\u0130ade \u0130stek Yan\u0131t\u0131",
                    "type": "string"
                },
                "requestReason": {
                    "description": "Request Reason\n\u0130stek Nedeni",
                    "type": "string"
                },
                "returnReason": {
                    "description": "Return Reason\n\u0130ade Nedeni",
                    "type": "string"
                },
                "isShipmentRejected": {
                    "description": "Is Recipient Rejected Shipment?\nAl\u0131c\u0131 G\u00f6nderiyi Red Mi Etti?",
                    "type": "integer",
                    "format": "int32"
                },
                "deliveryTime": {
                    "description": "Shipment Delivery DateTime\nTeslim Tarihi",
                    "type": "string"
                },
                "deliveryTo": {
                    "description": "Name and Surname who delivery to shipment.\nG\u00f6nderiyi teslim alan ad\u0131 ve soyad\u0131.",
                    "type": "string"
                },
                "answer": {
                    "description": "Answer \r\nYan\u0131t",
                    "type": "string"
                },
                "answerDate": {
                    "description": "Answer Date\nYan\u0131t tarihi",
                    "type": "string"
                },
                "personWhoAnswered": {
                    "description": "Person Who Answered\nYan\u0131tlayan Ki\u015fi",
                    "type": "string"
                },
                "ipAddressWhoAnswered": {
                    "description": "IP Address Who Answered\nYan\u0131tlayan Ki\u015fin IP Adresi",
                    "type": "string"
                },
                "codAmountFinalTotal": {
                    "description": "Cash on Delivery Amount Final Total\nKap\u0131da \u00d6deme Toplam Miktar\u0131",
                    "type": "string"
                },
                "codAmount": {
                    "description": "Cash on Delivery Amount\nKap\u0131da \u00d6deme Miktar\u0131",
                    "type": "string"
                },
                "packagingType": {
                    "description": "Type of Order:  1:DOSYA, 2:M\u0130, 3:PAKET, 4:KOL\u0130\nKargo Cinsi",
                    "type": "string"
                },
                "paymentType": {
                    "description": "Payment Type of Order: 1:GONDERICI_ODER, 2:ALICI_ODER,3:PLATFORM_ODER\n\u00d6deme \u015eekli",
                    "type": "string"
                },
                "deliveryType": {
                    "description": "Delivery Type of Order: 1:ADRESE_TESLIM, 2:ALICISI_HABERL\u0130 \r\nTeslim \u015eekli",
                    "type": "string"
                },
                "shipmentServiceType": {
                    "description": "Shipment Service Type: 1:STANDART_TESL\u0130MAT, 7:GUN\u0130C\u0130_TESL\u0130MAT, 8:AK\u015eAM_TESL\u0130MAT\nG\u00f6nderi Tipi",
                    "type": "string"
                },
                "isCOD": {
                    "description": "Indicates whether it is Cash On Delivery.\nKap\u0131da \u00d6deme mi?",
                    "type": "integer",
                    "format": "int32"
                },
                "isConfirmed": {
                    "description": "Is Confirmed?\nOnayland\u0131 m\u0131?",
                    "type": "integer",
                    "format": "int32"
                },
                "isRecipientRejected": {
                    "description": "Is Recipient Rejected\nAl\u0131c\u0131 Red Mi Etti?",
                    "type": "integer",
                    "format": "int32"
                },
                "isDelivered": {
                    "description": "Is Shipment Delivered?\nG\u00f6nderi Teslim Edildi Mi?",
                    "type": "integer",
                    "format": "int32"
                },
                "isEMailSended": {
                    "description": "Is Mail Sended ?\nMail G\u00f6nderildi Mi?",
                    "type": "integer",
                    "format": "int32"
                },
                "isAnswered": {
                    "description": "Is Answered?\nM\u00fc\u015fteri Yan\u0131tlad\u0131 M\u0131?",
                    "type": "integer",
                    "format": "int32"
                },
                "isAnswerApprovedorRejected": {
                    "description": "Is Answer Approved or Rejected ?\nCevap Onayland\u0131 m\u0131? Ya da Red Mi Edildi ?",
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
        "GetTtiListResponse": {
            "title": "GetTtiListResponse",
            "type": "object",
            "properties": {
                "ttiNo": {
                    "type": "string"
                },
                "courierCode": {
                    "type": "string"
                },
                "courierName": {
                    "type": "string"
                },
                "ttiDate": {
                    "type": "string"
                },
                "cargoBarcode": {
                    "type": "string"
                },
                "kgDesi": {
                    "type": "string"
                },
                "amount": {
                    "type": "string"
                },
                "recipient": {
                    "type": "string"
                },
                "shipper": {
                    "type": "string"
                },
                "customerNo": {
                    "type": "string"
                },
                "shipmentId": {
                    "type": "string"
                },
                "invoiceSerial": {
                    "type": "string"
                },
                "invoiceNumber": {
                    "type": "string"
                },
                "customerRefNo": {
                    "type": "string"
                },
                "pieceNumber": {
                    "type": "string"
                },
                "shipmentDate": {
                    "type": "string"
                }
            }
        },
        "GetShipmentInfoByShipmentIdResponse": {
            "title": "GetShipmentInfoByShipmentIdResponse",
            "type": "object",
            "properties": {
                "invoiceSerial": {
                    "type": "string"
                },
                "invoiceNumber": {
                    "type": "string"
                },
                "shipmentId": {
                    "type": "string"
                },
                "customerRefNo": {
                    "type": "string"
                },
                "billOfLandingId": {
                    "type": "string"
                },
                "shipmentDate": {
                    "type": "string"
                },
                "estimatedDeliveryDate": {
                    "type": "string"
                },
                "shipper": {
                    "type": "string"
                },
                "recipient": {
                    "type": "string"
                },
                "amount": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "kgDesi": {
                    "type": "string"
                },
                "shipperBranch": {
                    "type": "string"
                },
                "receivingBranch": {
                    "type": "string"
                },
                "deliveryType": {
                    "type": "string"
                },
                "deliveryDate": {
                    "type": "string"
                },
                "deliveryTime": {
                    "type": "string"
                },
                "deliveryTo": {
                    "type": "string"
                },
                "shipmentStatus": {
                    "type": "string"
                },
                "shipmentStatusExplanation": {
                    "type": "string"
                },
                "statusDateTime": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "api-key-1": {
            "description": "asepetcioglu@mngkargo.com.tr",
            "in": "header",
            "name": "X-IBM-Client-Id",
            "type": "apiKey"
        },
        "api-key-2": {
            "description": "",
            "in": "header",
            "name": "X-IBM-Client-Secret",
            "type": "apiKey"
        }
    },
    "security": [
        {
            "api-key-2": [],
            "api-key-1": []
        }
    ],
    "produces": [
        "asepetcioglu@mngkargo.com.tr"
    ],
    "schemes": [
        "https"
    ],
    "host": "testapi.mngkargo.com.tr"
}