{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "Plus Command API",
        "description": "Detayl\u0131 ve Pazaryeri sipari\u015fleri olu\u015fturan, sipari\u015f teslimat\u0131n\u0131 iptal eden, al\u0131c\u0131 olu\u015fturan, g\u00f6nderi teslimant problemlerine yan\u0131t veren metodlar\u0131n yer ald\u0131\u011f\u0131 API'd\u0131r. | It is the API that creates Detailed Order and Market Place Order, cancels order delivery, create recipient, answers shipment delivery problems.",
        "termsOfService": "http://swagger.io/terms/"
    },
    "basePath": "/mngapi/api/pluscmdapi",
    "paths": {
        "/createDetailedOrder": {
            "post": {
                "tags": [
                    "PlusCommand"
                ],
                "summary": "Create Detailed Order",
                "description": "'Detayl\u0131' sipari\u015f olu\u015fturur. Al\u0131c\u0131 ve g\u00f6nderici bilgisi de\u011ferleri doldurulurken ya CustomerId verilir ya da Al\u0131c\u0131 ve G\u00f6nderici'nin FullName, CityCode, DistrictCode, Address alanlar\u0131 ve MobilePhoneNumber, HomePhoneNumber, BussinessPhoneNumber' dan herhangi biri girilmelidir. | Creates detailed type of order. When you fill Recipient, Shipper areas either you set CustomerId or Recipient's and Shipper's FullName, CityCode, DistrictCode, Address and one of the MobilePhoneNumber, HomePhoneNumber, BussinessPhoneNumber.",
                "operationId": "CreateDetailedOrderPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "createDetailedOrderRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CreateDetailedOrderRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detailed order created",
                        "schema": {
                            "$ref": "#/definitions/CreateDetailedOrderResponse"
                        },
                        "examples": {
                            "application/json": {
                                "orderInvoiceId": "456764543",
                                "orderInvoiceDetailId": "25423565",
                                "shipperBranchCode": "1345"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/createRecipient": {
            "post": {
                "tags": [
                    "PlusCommand"
                ],
                "summary": "Create recipient.",
                "description": "Al\u0131c\u0131 olu\u015fturur. | Creates Recipient.",
                "operationId": "CreateRecipientPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "createRecipientRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CreateRecipientRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Recipient created",
                        "schema": {
                            "$ref": "#/definitions/CreateRecipientResponse"
                        },
                        "examples": {
                            "application/json": {
                                "orderInvoiceId": "456764543",
                                "orderInvoiceDetailId": "25423565",
                                "shipperBranchCode": "1345"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/createMarketPlaceOrder": {
            "post": {
                "tags": [
                    "PlusCommand"
                ],
                "summary": "Create MarketPlace Order",
                "description": "'Pazaryeri' sipari\u015fi olu\u015fturur. MarketPlaceShortCode ve MarketPlaceSaleCode zorunludur.  | Creates Market Place type of order.  MarketPlaceShortCode and MarketPlaceSaleCode are required.",
                "operationId": "CreateMarketPlaceOrderPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "createMarketPlaceOrderRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CreateMarketPlaceOrderRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "MarketPlace order created",
                        "schema": {
                            "$ref": "#/definitions/CreateMarketPlaceOrderResponse"
                        },
                        "examples": {
                            "application/json": {
                                "orderInvoiceId": "456764543",
                                "orderInvoiceDetailId": "25423565",
                                "shipperBranchCode": "1345"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/cancelOrderDelivery": {
            "post": {
                "tags": [
                    "PlusCommand"
                ],
                "summary": "Cancel Order Delivery",
                "description": "\u0130lgili referans numaras\u0131na ait sipari\u015f teslimat\u0131n\u0131 iptal eder. \u0130ptal A\u00e7\u0131klamas\u0131 yaz\u0131lmal\u0131d\u0131r. | Cancels order delivery of the relevant reference number. You must set cancel description.",
                "operationId": "CancelOrderDeliveryPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "cancelOrderDeliveryRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CancelOrderDeliveryRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order or delivery canceled",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/answerShipmentDeliveryProblem": {
            "post": {
                "tags": [
                    "PlusCommand"
                ],
                "summary": "Answer Shipment Delivery Problem",
                "description": "\u0130lgili g\u00f6nderi teslimat problem numaras\u0131na ait g\u00f6nderi teslimat problemine yan\u0131t vermeyi sa\u011flar. | Provides to answer shipment delivery problem of the relevant shipment delivery problem number.",
                "operationId": "AnswerShipmentDeliveryProblemPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "answerShipmentDeliveryProblemRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/AnswerShipmentDeliveryProblemRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Answered"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Shipment delivery problem not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/marketPlaceCancelOrder": {
            "post": {
                "description": "",
                "summary": "MarketPlaceCancelOrder_POST",
                "tags": [
                    "PlusCommand"
                ],
                "operationId": "MarketPlaceCancelOrder_POST",
                "deprecated": false,
                "produces": [
                    "application/json"
                ],
                "consumes": [
                    "application/json-patch+json"
                ],
                "parameters": [
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "required": false,
                        "enum": [
                            "application/json-patch+json"
                        ],
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": false,
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/MarketPlaceCancelOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string",
                            "default": ""
                        },
                        "headers": []
                    },
                    "500": {
                        "description": "Server Error",
                        "headers": []
                    }
                }
            }
        },
        "/updateMpSender": {
            "post": {
                "description": "",
                "summary": "UpdateMpSender_POST",
                "tags": [
                    "PlusCommand"
                ],
                "operationId": "UpdateMpSender_POST",
                "deprecated": false,
                "produces": [
                    "application/json"
                ],
                "consumes": [
                    "application/json-patch+json"
                ],
                "parameters": [
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "required": true,
                        "type": "string",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "required": false,
                        "enum": [
                            "application/json-patch+json"
                        ],
                        "type": "string",
                        "description": ""
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": false,
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/UpdateMpSenderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "headers": []
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        },
                        "headers": []
                    },
                    "500": {
                        "description": "Server Error",
                        "headers": []
                    }
                }
            }
        }
    },
    "definitions": {
        "CreateDetailedOrderRequest": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/Order"
                },
                "orderPieceList": {
                    "uniqueItems": false,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderPieceList"
                    }
                },
                "shipper": {
                    "$ref": "#/definitions/Customer"
                },
                "recipient": {
                    "$ref": "#/definitions/Customer"
                }
            },
            "example": {
                "order": {
                    "referenceId": "SIPARIS34567",
                    "barcode": "SIPARIS34567",
                    "billOfLandingId": "\u0130rsaliye 1",
                    "isCOD": 0,
                    "codAmount": 0,
                    "shipmentServiceType": 1,
                    "packagingType": 1,
                    "content": "\u0130\u00e7erik 1",
                    "smsPreference1": 1,
                    "smsPreference2": 0,
                    "smsPreference3": 0,
                    "paymentType": 1,
                    "deliveryType": 1,
                    "description": "A\u00e7\u0131klama 1",
                    "marketPlaceShortCode": "",
                    "marketPlaceSaleCode": "",
                    "pudoId": ""
                },
                "orderPieceList": [
                    {
                        "barcode": "SIPARIS34567_PARCA1",
                        "desi": 2,
                        "kg": 1,
                        "content": "Par\u00e7a a\u00e7\u0131klama 1"
                    },
                    {
                        "barcode": "SIPARIS34567_PARCA2",
                        "desi": 2,
                        "kg": 3,
                        "content": "Par\u00e7a a\u00e7\u0131klama 2"
                    }
                ],
                "shipper": {
                    "customerId": 58513278,
                    "refCustomerId": "",
                    "cityCode": 0,
                    "districtCode": 0,
                    "cityName": "",
                    "districtName": "",
                    "address": "",
                    "bussinessPhoneNumber": "",
                    "email": "",
                    "taxOffice": "",
                    "taxNumber": "",
                    "fullName": "",
                    "homePhoneNumber": "",
                    "mobilePhoneNumber": ""
                },
                "recipient": {
                    "customerId": 146405879,
                    "refCustomerId": "",
                    "cityCode": 0,
                    "districtCode": 0,
                    "cityName": "",
                    "districtName": "",
                    "address": "",
                    "bussinessPhoneNumber": "",
                    "email": "ornek2@ornekemail.com",
                    "taxOffice": "",
                    "taxNumber": "",
                    "fullName": "",
                    "homePhoneNumber": "",
                    "mobilePhoneNumber": ""
                }
            }
        },
        "Order": {
            "required": [
                "referenceId",
                "shipmentServiceType",
                "packagingType",
                "content",
                "smsPreference1",
                "smsPreference2",
                "smsPreference3",
                "paymentType",
                "deliveryType",
                "description"
            ],
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order, ReferenceId must be unique foreach order. ReferenceId must be uppercase.\r\nSipari\u015f Numaras\u0131, Sipari\u015f numaras\u0131 her sipari\u015f i\u00e7in benzersiz olmal\u0131d\u0131r. Sipari\u015f numaras\u0131 b\u00fcy\u00fckharflerden olu\u015fmal\u0131d\u0131r.",
                    "type": "string"
                },
                "barcode": {
                    "description": "Barcode must be same with ReferenceId. Barcode must be uppercase.\r\nBarkod ReferenceId ile ayn\u0131 olmal\u0131d\u0131r. Barkod b\u00fcy\u00fckharflerden olu\u015fmal\u0131d\u0131r.",
                    "type": "string"
                },
                "billOfLandingId": {
                    "description": "Bill Of LandingId\r\n\u0130rsaliye Numaras\u0131",
                    "type": "string"
                },
                "isCOD": {
                    "format": "int32",
                    "description": "Indicates whether it is Cash On Delivery.\r\nKap\u0131da \u00d6deme mi?",
                    "type": "integer"
                },
                "codAmount": {
                    "format": "double",
                    "description": "Cash on Delivery Amount\r\nKap\u0131da \u00d6deme Miktar\u0131",
                    "type": "number"
                },
                "shipmentServiceType": {
                    "format": "int32",
                    "description": "Shipment Service Type: 1:STANDART_TESL\u0130MAT, 7:GUN\u0130C\u0130_TESL\u0130MAT, 8:AK\u015eAM_TESL\u0130MAT\r\nG\u00f6nderi Tipi",
                    "type": "integer"
                },
                "packagingType": {
                    "format": "int32",
                    "description": "Package Type of Order:  1:DOSYA, 2:M\u0130, 3:PAKET, 4:KOL\u0130\r\nKargo Cinsi",
                    "type": "integer"
                },
                "content": {
                    "description": "Content\r\nGenel \u0130\u00e7erik Bilgisi",
                    "type": "string"
                },
                "smsPreference1": {
                    "format": "int32",
                    "description": "SMSPreference Is Send SMS to Recipient When Shipment Reached to Destination Branch\r\nKargo var\u0131\u015f \u015fubesine ula\u015ft\u0131\u011f\u0131nda al\u0131c\u0131ya SMS gitsin mi?",
                    "type": "integer"
                },
                "smsPreference2": {
                    "format": "int32",
                    "description": "Is Send SMS to Recipient When Shpiment First Prepare\r\nKargo ilk haz\u0131rland\u0131\u011f\u0131nda al\u0131c\u0131ya SMS gitsin mi?",
                    "type": "integer"
                },
                "smsPreference3": {
                    "format": "int32",
                    "description": "Is Send SMS to Shipper When Shipment Delivered\r\nKargo teslim edildi\u011finde g\u00f6ndericiye SMS gitsin mi?",
                    "type": "integer"
                },
                "paymentType": {
                    "format": "int32",
                    "description": "Payment Type of Order: 1:GONDERICI_ODER, 2:ALICI_ODER,3:PLATFORM_ODER. Method CreateOrder does not apply to payment type 3. \r\n\u00d6deme \u015eekli, CreateOrder metodunda 3 tipindeki \u00f6deme \u015fekli ge\u00e7erli de\u011fildir.",
                    "type": "integer"
                },
                "deliveryType": {
                    "format": "int32",
                    "description": "Delivery Type of Order: 1:ADRESE_TESLIM, 2:ALICISI_HABERL\u0130 \r\nTeslim \u015eekli",
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "marketPlaceShortCode": {
                    "description": "Short MarketPlace Code of Order : ex: TRND, N11, GG, VIVE\r\nPazaryeri Kodu  \u00f6rne\u011fin: TRND, N11, GG, VIVE",
                    "type": "string"
                },
                "marketPlaceSaleCode": {
                    "description": "Sale Code of MarketPlace\r\nPazaryeri Sat\u0131\u015f Kodu",
                    "type": "string"
                }
            }
        },
        "OrderPieceList": {
            "required": [
                "barcode",
                "desi",
                "kg"
            ],
            "type": "object",
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "desi": {
                    "format": "int32",
                    "type": "integer"
                },
                "kg": {
                    "format": "int32",
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "Customer": {
            "type": "object",
            "properties": {
                "customerId": {
                    "format": "int64",
                    "description": "Identity Number of Customer \r\nM\u00fc\u015fteri Numaras\u0131",
                    "type": "integer"
                },
                "refCustomerId": {
                    "description": "Identity Number of Customer in their's own system.\r\nM\u00fc\u015fterinin kendi sistemindeki numaras\u0131",
                    "type": "string"
                },
                "cityCode": {
                    "format": "int32",
                    "description": "Code of City you can provide code information from CBS Info API.\r\n\u015eehir Kodu, CBS Info API'den kod bilgisi al\u0131nabilir.",
                    "type": "integer"
                },
                "districtCode": {
                    "format": "int32",
                    "description": "Code of District you can provide code information from CBS Info API.\r\n\u0130l\u00e7e Kodu, CBS Info API'den kod bilgisi al\u0131nabilir.",
                    "type": "integer"
                },
                "address": {
                    "type": "string"
                },
                "bussinessPhoneNumber": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "taxOffice": {
                    "description": "Tax Office\r\nVergi Dairesi",
                    "type": "string"
                },
                "taxNumber": {
                    "description": "Tax Number\r\nVergi Numaras\u0131",
                    "type": "string"
                },
                "fullName": {
                    "description": "Full Name of Customer\r\nM\u00fc\u015fterinin Tam Ad\u0131",
                    "type": "string"
                },
                "homePhoneNumber": {
                    "type": "string"
                },
                "mobilePhoneNumber": {
                    "type": "string"
                }
            }
        },
        "CreateDetailedOrderResponse": {
            "type": "object",
            "properties": {
                "orderInvoiceId": {
                    "description": "Order Invoice Id \r\nSipari\u015f Fatura Numaras\u0131",
                    "type": "string"
                },
                "orderInvoiceDetailId": {
                    "description": "Order Invoice Detail Id\r\nSipari\u015f Detay Fatura Numaras\u0131",
                    "type": "string"
                },
                "shipperBranchCode": {
                    "description": "Shipper Branch Code\r\nG\u00f6nderici \u015eube Kodu",
                    "type": "string"
                }
            }
        },
        "CreateRecipientRequest": {
            "type": "object",
            "properties": {
                "recipient": {
                    "$ref": "#/definitions/Customer"
                }
            },
            "example": {
                "recipient": {
                    "customerId": "",
                    "refCustomerId": "",
                    "cityName": "",
                    "districtName": "",
                    "cityCode": 34,
                    "districtCode": 56,
                    "address": "Abidinpa\u015fa Mah. Kaynarca Sok. No:223 Daire:110",
                    "bussinessPhoneNumber": "",
                    "email": "ornek1@ornekemail.com",
                    "taxOffice": "Tuzla",
                    "taxNumber": "1234512345",
                    "fullName": "Ahmet Y\u0131lmaz",
                    "homePhoneNumber": "",
                    "mobilePhoneNumber": "5555555555"
                }
            }
        },
        "CreateRecipientResponse": {
            "type": "object",
            "properties": {
                "orderInvoiceId": {
                    "description": "Order Invoice Id \r\nSipari\u015f Fatura Numaras\u0131",
                    "type": "string"
                },
                "orderInvoiceDetailId": {
                    "description": "Order Invoice Detail Id\r\nSipari\u015f Detay Fatura Numaras\u0131",
                    "type": "string"
                },
                "shipperBranchCode": {
                    "description": "Shipper Branch Code\r\nG\u00f6nderici \u015eube Kodu",
                    "type": "string"
                }
            }
        },
        "CreateMarketPlaceOrderRequest": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/Order"
                },
                "orderPieceList": {
                    "uniqueItems": false,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderPieceList"
                    }
                }
            },
            "example": {
                "order": {
                    "referenceId": "SIPARIS34567",
                    "barcode": "SIPARIS34567",
                    "billOfLandingId": "\u0130rsaliye 1",
                    "isCOD": 0,
                    "codAmount": 0,
                    "shipmentServiceType": 1,
                    "packagingType": 1,
                    "content": "\u0130\u00e7erik 1",
                    "smsPreference1": 1,
                    "smsPreference2": 0,
                    "smsPreference3": 0,
                    "paymentType": 1,
                    "deliveryType": 1,
                    "description": "A\u00e7\u0131klama 1",
                    "marketPlaceShortCode": "",
                    "marketPlaceSaleCode": ""
                },
                "orderPieceList": [
                    {
                        "barcode": "SIPARIS34567_PARCA1",
                        "desi": 2,
                        "kg": 1,
                        "content": "Par\u00e7a a\u00e7\u0131klama 1"
                    },
                    {
                        "barcode": "SIPARIS34567_PARCA2",
                        "desi": 2,
                        "kg": 3,
                        "content": "Par\u00e7a a\u00e7\u0131klama 2"
                    }
                ]
            }
        },
        "CreateMarketPlaceOrderResponse": {
            "type": "object",
            "properties": {
                "orderInvoiceId": {
                    "description": "Order Invoice Id \r\nSipari\u015f Fatura Numaras\u0131",
                    "type": "string"
                },
                "orderInvoiceDetailId": {
                    "description": "Order Invoice Detail Id\r\nSipari\u015f Detay Fatura Numaras\u0131",
                    "type": "string"
                },
                "shipperBranchCode": {
                    "description": "Shipper Branch Code\r\nG\u00f6nderici \u015eube Kodu",
                    "type": "string"
                }
            }
        },
        "CancelOrderDeliveryRequest": {
            "required": [
                "referenceId",
                "description"
            ],
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order\r\nSipari\u015f Numaras\u0131",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "example": {
                "referenceId": "S1094",
                "description": "A\u00e7\u0131klama 1"
            }
        },
        "AnswerShipmentDeliveryProblemRequest": {
            "required": [
                "shipmentId",
                "shipmentDeliveryProblemId",
                "approveOrCancel",
                "anwser"
            ],
            "type": "object",
            "properties": {
                "shipmentId": {
                    "description": "Identity Number of Shipment\r\nG\u00f6nderi Numaras\u0131",
                    "type": "string"
                },
                "shipmentDeliveryProblemId": {
                    "format": "int32",
                    "type": "integer"
                },
                "approveOrCancel": {
                    "format": "int32",
                    "description": "Approve: 1 , Cancel : 0",
                    "type": "integer"
                },
                "anwser": {
                    "description": "Shipment delivery problem answer\r\nG\u00f6nderi teslimat problemine yan\u0131t",
                    "type": "string"
                }
            },
            "example": {
                "shipmentId": 610291545961,
                "shipmentDeliveryProblemId": 1116,
                "approveOrCancel": 1,
                "anwser": "Cevap 1"
            }
        },
        "MarketPlaceCancelOrderRequest": {
            "title": "MarketPlaceCancelOrderRequest",
            "type": "object",
            "properties": {
                "referenceId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "referenceId",
                "description"
            ]
        },
        "UpdateMpSenderRequest": {
            "title": "UpdateMpSenderRequest",
            "type": "object",
            "properties": {
                "marketPlaceRefSenderCode": {
                    "type": "string"
                },
                "marketPlaceShortCode": {
                    "type": "string"
                },
                "marketPlaceSaleCode": {
                    "type": "string"
                }
            },
            "required": [
                "marketPlaceShortCode",
                "marketPlaceSaleCode"
            ]
        },
        "ProblemDetails": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "status": {
                    "format": "int32",
                    "type": "integer"
                },
                "detail": {
                    "type": "string"
                },
                "instance": {
                    "type": "string"
                }
            },
            "additionalProperties": {
                "type": "object"
            }
        }
    },
    "securityDefinitions": {
        "api-key-1": {
            "description": "myalcin@mngkargo.com.tr",
            "in": "header",
            "name": "X-IBM-Client-Id",
            "type": "apiKey"
        },
        "api-key-2": {
            "description": "",
            "in": "header",
            "name": "X-IBM-Client-Secret",
            "type": "apiKey"
        }
    },
    "security": [
        {
            "api-key-2": [],
            "api-key-1": []
        }
    ],
    "schemes": [
        "https"
    ],
    "host": "testapi.mngkargo.com.tr"
}