{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "Standard Command API",
        "description": "'Normal', '\u0130ade' sipari\u015fleri olu\u015fturan, sipari\u015fi g\u00fcncelleyen ve sipari\u015fi iptal eden metodlar\u0131n bulundu\u011fu API'dir. |This API inculdes methods that creates Normal, Return types of order, updates order and cancels order.",
        "termsOfService": "http://swagger.io/terms/"
    },
    "basePath": "/mngapi/api/standardcmdapi",
    "paths": {
        "/createOrder": {
            "post": {
                "tags": [
                    "StandardCommand"
                ],
                "summary": "Create Order",
                "description": "'Normal' sipari\u015f olu\u015fturur. Al\u0131c\u0131 bilgisi de\u011ferleri doldurulurken ya CustomerId verilir ya da Al\u0131c\u0131 FullName, CityCode, DistrictCode, Address alanlar\u0131 ve MobilePhoneNumber, HomePhoneNumber, BussinessPhoneNumber'dan herhangi biri girilmelidir. | Creates normal type of order. When you fill Recipient areas either you set CustomerId or Recipient' s FullName, CityCode, DistrictCode, Address and one of the MobilePhoneNumber, HomePhoneNumber, BussinessPhoneNumber.",
                "operationId": "CreateOrderPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "createOrderRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CreateOrderRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order created",
                        "schema": {
                            "$ref": "#/definitions/CreateOrderResponse"
                        },
                        "examples": {
                            "application/json": {
                                "orderInvoiceId": "456764543",
                                "orderInvoiceDetailId": "25423565",
                                "shipperBranchCode": "1345",
                                "referenceId": "YourReferenceId"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/createReturnOrder": {
            "post": {
                "tags": [
                    "StandardCommand"
                ],
                "summary": "Create Return Order",
                "description": "'\u0130ade' sipari\u015f olu\u015fturur. G\u00f6nderici bilgisi de\u011ferleri doldurulurken ya CustomerId verilir ya da G\u00f6nderici FullName, CityCode, DistrictCode, Address alanlar\u0131 ve MobilePhoneNumber, HomePhoneNumber, BussinessPhoneNumber'dan herhangi biri girilmelidir. | Creates return type of order. When you fill shipper areas either you set CustomerId or Shipper's FullName, CityCode, DistrictCode, Address and one of the MobilePhoneNumber, HomePhoneNumber, BussinessPhoneNumber.",
                "operationId": "CreateReturnOrderPost",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "createReturnOrderRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/CreateReturnOrderRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Return order created",
                        "schema": {
                            "$ref": "#/definitions/CreateReturnOrderResponse"
                        },
                        "examples": {
                            "application/json": {
                                "orderInvoiceId": "456764543",
                                "orderInvoiceDetailId": "25423565",
                                "shipperBranchCode": "1345",
                                "referenceId": "YourReferenceId",
                                "returnOrderLabelURL": "https://mn.tc?rtnid=EPPSVVXJ"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/updateorder": {
            "put": {
                "tags": [
                    "StandardCommand"
                ],
                "summary": "Update Order",
                "description": "\u0130lgili referans numaras\u0131na ait sipari\u015fi g\u00fcnceller. | Updates the order of the relevant reference number.",
                "operationId": "UpdateorderPut",
                "consumes": [
                    "application/json-patch+json",
                    "application/json",
                    "text/json",
                    "application/*+json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "updatePieceRequest",
                        "in": "body",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/UpdateOrderRequest"
                        }
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        },
        "/cancelorder/{refrenceId}": {
            "put": {
                "tags": [
                    "StandardCommand"
                ],
                "summary": "Cancel Order",
                "description": "\u0130lgili referans numaras\u0131na ait sipari\u015fi iptal eder. | Cancels the order of the relevant reference number.",
                "operationId": "CancelorderByRefrenceIdPut",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "refrenceId",
                        "in": "path",
                        "description": "cancels order according to given referenceId",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "x-api-version",
                        "in": "header",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order canceled",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "CreateOrderRequest": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/Order"
                },
                "orderPieceList": {
                    "uniqueItems": false,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderPieceList"
                    }
                },
                "recipient": {
                    "$ref": "#/definitions/Customer"
                }
            },
            "example": {
                "order": {
                    "referenceId": "SIPARIS34567",
                    "barcode": "SIPARIS34567",
                    "billOfLandingId": "\u0130rsaliye 1",
                    "isCOD": 0,
                    "codAmount": 0,
                    "shipmentServiceType": 1,
                    "packagingType": 1,
                    "content": "\u0130\u00e7erik 1",
                    "smsPreference1": 1,
                    "smsPreference2": 0,
                    "smsPreference3": 0,
                    "paymentType": 1,
                    "deliveryType": 1,
                    "description": "A\u00e7\u0131klama 1",
                    "marketPlaceShortCode": "",
                    "marketPlaceSaleCode": "",
                    "pudoId": ""
                },
                "orderPieceList": [
                    {
                        "barcode": "SIPARIS34567_PARCA1",
                        "desi": 2,
                        "kg": 1,
                        "content": "Par\u00e7a a\u00e7\u0131klama 1"
                    },
                    {
                        "barcode": "SIPARIS34567_PARCA2",
                        "desi": 2,
                        "kg": 3,
                        "content": "Par\u00e7a a\u00e7\u0131klama 2"
                    }
                ],
                "recipient": {
                    "customerId": 58513278,
                    "refCustomerId": "",
                    "cityCode": 0,
                    "cityName": "",
                    "districtName": "",
                    "districtCode": 0,
                    "address": "",
                    "bussinessPhoneNumber": "",
                    "email": "",
                    "taxOffice": "",
                    "taxNumber": "",
                    "fullName": "",
                    "homePhoneNumber": "",
                    "mobilePhoneNumber": ""
                }
            }
        },
        "Order": {
            "required": [
                "referenceId",
                "shipmentServiceType",
                "packagingType",
                "content",
                "smsPreference1",
                "smsPreference2",
                "smsPreference3",
                "paymentType",
                "deliveryType",
                "description"
            ],
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order, ReferenceId must be unique foreach order. ReferenceId must be uppercase.\r\nSipari\u015f Numaras\u0131, Sipari\u015f numaras\u0131 her sipari\u015f i\u00e7in benzersiz olmal\u0131d\u0131r. Sipari\u015f numaras\u0131 b\u00fcy\u00fckharflerden olu\u015fmal\u0131d\u0131r.",
                    "type": "string"
                },
                "barcode": {
                    "description": "Barcode must be same with ReferenceId. Barcode must be uppercase.\r\nBarkod ReferenceId ile ayn\u0131 olmal\u0131d\u0131r. Barkod b\u00fcy\u00fckharflerden olu\u015fmal\u0131d\u0131r.",
                    "type": "string"
                },
                "billOfLandingId": {
                    "description": "Bill Of LandingId\r\n\u0130rsaliye Numaras\u0131",
                    "type": "string"
                },
                "isCOD": {
                    "format": "int32",
                    "description": "Indicates whether it is Cash On Delivery.\r\nKap\u0131da \u00d6deme mi?",
                    "type": "integer"
                },
                "codAmount": {
                    "format": "double",
                    "description": "Cash on Delivery Amount\r\nKap\u0131da \u00d6deme Miktar\u0131",
                    "type": "number"
                },
                "shipmentServiceType": {
                    "format": "int32",
                    "description": "Shipment Service Type: 1:STANDART_TESL\u0130MAT, 7:GUN\u0130C\u0130_TESL\u0130MAT, 8:AK\u015eAM_TESL\u0130MAT\r\nG\u00f6nderi Tipi",
                    "type": "integer"
                },
                "packagingType": {
                    "format": "int32",
                    "description": "Package Type of Order:  1:DOSYA, 2:M\u0130, 3:PAKET, 4:KOL\u0130\r\nKargo Cinsi",
                    "type": "integer"
                },
                "content": {
                    "description": "Content\r\nGenel \u0130\u00e7erik Bilgisi",
                    "type": "string"
                },
                "smsPreference1": {
                    "format": "int32",
                    "description": "SMSPreference Is Send SMS to Recipient When Shipment Reached to Destination Branch\r\nKargo var\u0131\u015f \u015fubesine ula\u015ft\u0131\u011f\u0131nda al\u0131c\u0131ya SMS gitsin mi?",
                    "type": "integer"
                },
                "smsPreference2": {
                    "format": "int32",
                    "description": "Is Send SMS to Recipient When Shpiment First Prepare\r\nKargo ilk haz\u0131rland\u0131\u011f\u0131nda al\u0131c\u0131ya SMS gitsin mi?",
                    "type": "integer"
                },
                "smsPreference3": {
                    "format": "int32",
                    "description": "Is Send SMS to Shipper When Shipment Delivered\r\nKargo teslim edildi\u011finde g\u00f6ndericiye SMS gitsin mi?",
                    "type": "integer"
                },
                "paymentType": {
                    "format": "int32",
                    "description": "Payment Type of Order: 1:GONDERICI_ODER, 2:ALICI_ODER,3:PLATFORM_ODER. Method CreateOrder does not apply to payment type 3. \r\n\u00d6deme \u015eekli, CreateOrder metodunda 3 tipindeki \u00f6deme \u015fekli ge\u00e7erli de\u011fildir.",
                    "type": "integer"
                },
                "deliveryType": {
                    "format": "int32",
                    "description": "Delivery Type of Order: 1:ADRESE_TESLIM, 2:ALICISI_HABERL\u0130 \r\nTeslim \u015eekli",
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "marketPlaceShortCode": {
                    "description": "Short MarketPlace Code of Order : ex: TRND, N11, GG, VIVE\r\nPazaryeri Kodu  \u00f6rne\u011fin: TRND, N11, GG, VIVE",
                    "type": "string"
                },
                "marketPlaceSaleCode": {
                    "description": "Sale Code of MarketPlace\r\nPazaryeri Sat\u0131\u015f Kodu",
                    "type": "string"
                }
            }
        },
        "OrderPieceList": {
            "required": [
                "barcode",
                "desi",
                "kg"
            ],
            "type": "object",
            "properties": {
                "barcode": {
                    "type": "string"
                },
                "desi": {
                    "format": "int32",
                    "type": "integer"
                },
                "kg": {
                    "format": "int32",
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                }
            }
        },
        "Customer": {
            "type": "object",
            "properties": {
                "customerId": {
                    "format": "int64",
                    "description": "Identity Number of Customer \r\nM\u00fc\u015fteri Numaras\u0131",
                    "type": "integer"
                },
                "refCustomerId": {
                    "description": "Identity Number of Customer in their's own system.\r\nM\u00fc\u015fterinin kendi sistemindeki numaras\u0131",
                    "type": "string"
                },
                "cityCode": {
                    "format": "int32",
                    "description": "Code of City you can provide code information from CBS Info API.\r\n\u015eehir Kodu, CBS Info API'den kod bilgisi al\u0131nabilir.",
                    "type": "integer"
                },
                "districtCode": {
                    "format": "int32",
                    "description": "Code of District you can provide code information from CBS Info API.\r\n\u0130l\u00e7e Kodu, CBS Info API'den kod bilgisi al\u0131nabilir.",
                    "type": "integer"
                },
                "address": {
                    "type": "string"
                },
                "bussinessPhoneNumber": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "taxOffice": {
                    "description": "Tax Office\r\nVergi Dairesi",
                    "type": "string"
                },
                "taxNumber": {
                    "description": "Tax Number\r\nVergi Numaras\u0131",
                    "type": "string"
                },
                "fullName": {
                    "description": "Full Name of Customer\r\nM\u00fc\u015fterinin Tam Ad\u0131",
                    "type": "string"
                },
                "homePhoneNumber": {
                    "type": "string"
                },
                "mobilePhoneNumber": {
                    "type": "string"
                }
            }
        },
        "CreateOrderResponse": {
            "type": "object",
            "properties": {
                "orderInvoiceId": {
                    "description": "Order Invoice Id \r\nSipari\u015f Fatura Numaras\u0131",
                    "type": "string"
                },
                "orderInvoiceDetailId": {
                    "description": "Order Invoice Detail Id\r\nSipari\u015f Detay Fatura Numaras\u0131",
                    "type": "string"
                },
                "shipperBranchCode": {
                    "description": "Shipper Branch Code\r\nG\u00f6nderici \u015eube Kodu",
                    "type": "string"
                },
                "referenceId": {
                    "description": "Customer Reference Id\r\nM\u00fc\u015fteri Referans Numaras\u0131",
                    "type": "string"
                }
            }
        },
        "CreateReturnOrderResponse": {
            "type": "object",
            "properties": {
                "orderInvoiceId": {
                    "description": "Order Invoice Id \r\nSipari\u015f Fatura Numaras\u0131",
                    "type": "string"
                },
                "orderInvoiceDetailId": {
                    "description": "Order Invoice Detail Id\r\nSipari\u015f Detay Fatura Numaras\u0131",
                    "type": "string"
                },
                "shipperBranchCode": {
                    "description": "Shipper Branch Code\r\nG\u00f6nderici \u015eube Kodu",
                    "type": "string"
                },
                "referenceId": {
                    "description": "Customer Reference Id\r\nM\u00fc\u015fteri Referans Numaras\u0131",
                    "type": "string"
                },
                "returnOrderLabelURL": {
                    "description": "Return Order Label URL\r\n\u0130ade Sipari\u015f Etiket URL'i",
                    "type": "string",
                    "maxLength": 0
                }
            }
        },
        "CreateReturnOrderRequest": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/Order"
                },
                "orderPieceList": {
                    "uniqueItems": false,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderPieceList"
                    }
                },
                "shipper": {
                    "$ref": "#/definitions/Customer"
                }
            },
            "example": {
                "order": {
                    "referenceId": "SIPARIS34567",
                    "barcode": "SIPARIS34567",
                    "billOfLandingId": "\u0130rsaliye 1",
                    "isCOD": 0,
                    "codAmount": 0,
                    "shipmentServiceType": 1,
                    "packagingType": 1,
                    "content": "\u0130\u00e7erik 1",
                    "smsPreference1": 1,
                    "smsPreference2": 0,
                    "smsPreference3": 0,
                    "paymentType": 1,
                    "deliveryType": 1,
                    "description": "A\u00e7\u0131klama 1",
                    "marketPlaceShortCode": "",
                    "marketPlaceSaleCode": ""
                },
                "orderPieceList": [
                    {
                        "barcode": "SIPARIS34567_PARCA1",
                        "desi": 2,
                        "kg": 1,
                        "content": "Par\u00e7a a\u00e7\u0131klama 1"
                    },
                    {
                        "barcode": "SIPARIS34567_PARCA2",
                        "desi": 2,
                        "kg": 3,
                        "content": "Par\u00e7a a\u00e7\u0131klama 2"
                    }
                ],
                "shipper": {
                    "customerId": 58513278,
                    "refCustomerId": "",
                    "cityCode": 0,
                    "districtCode": 0,
                    "cityName": "",
                    "districtName": "",
                    "address": "",
                    "bussinessPhoneNumber": "",
                    "email": "",
                    "taxOffice": "",
                    "taxNumber": "",
                    "fullName": "",
                    "homePhoneNumber": "",
                    "mobilePhoneNumber": ""
                }
            }
        },
        "UpdateOrderRequest": {
            "required": [
                "referenceId"
            ],
            "type": "object",
            "properties": {
                "referenceId": {
                    "description": "Identity Number of Order, ReferenceId must be unique foreach order.\r\nSipari\u015f Numaras\u0131 , Sipari\u015f numaras\u0131 her sipari\u015f i\u00e7in benzersiz olmal\u0131d\u0131r.",
                    "type": "string"
                },
                "billOfLandingId": {
                    "description": "Bill Of LandingId\r\n\u0130rsaliye Numaras\u0131",
                    "type": "string"
                },
                "isCOD": {
                    "format": "int32",
                    "description": "Indicates whether it is Cash On Delivery.\r\nKap\u0131da \u00d6deme mi?",
                    "type": "integer"
                },
                "codAmount": {
                    "format": "double",
                    "description": "Cash on Delivery Amount\r\nKap\u0131da \u00d6deme Miktar\u0131",
                    "type": "number"
                },
                "orderPieceList": {
                    "uniqueItems": false,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderPieceList"
                    }
                }
            },
            "example": {
                "referenceId": "SIPARIS34567",
                "billOfLandingId": "\u0130rsaliye 2",
                "isCOD": 0,
                "codAmount": 0,
                "orderPieceList": [
                    {
                        "barcode": "SIPARIS34567_PARCA1",
                        "desi": 3,
                        "kg": 1,
                        "content": "Par\u00e7a a\u00e7\u0131klama 1"
                    },
                    {
                        "barcode": "SIPARIS34567_PARCA2",
                        "desi": 2,
                        "kg": 3,
                        "content": "Par\u00e7a a\u00e7\u0131klama 2"
                    }
                ]
            }
        }
    },
    "securityDefinitions": {
        "api-key-1": {
            "description": "myalcin@mngkargo.com.tr",
            "in": "header",
            "name": "X-IBM-Client-Id",
            "type": "apiKey"
        },
        "api-key-2": {
            "description": "",
            "in": "header",
            "name": "X-IBM-Client-Secret",
            "type": "apiKey"
        }
    },
    "security": [
        {
            "api-key-2": [],
            "api-key-1": []
        }
    ],
    "schemes": [
        "https"
    ],
    "host": "testapi.mngkargo.com.tr"
}